language: python
python: 
  - "3.5"
sudo: required
services:
  - docker
script:
  - docker pull harshjv/texlive-2015
  - docker run --rm -it -v $(pwd):/var/texlive harshjv/texlive-2015 sudo bash run_docker.sh 
deploy:
  provider: releases
  api_key:
    secure: cA7bu/lDae7cW4r14bSBmTwk+s9Mt32z1jEaRpDpLcWFeT31lFeU47Y1ehjw9oHdSaxqwcSY9YmfL8+QCgiCizxzhpDv8zTV+xPISYUCIJH3QjDREvghm556QTacKQMdLzja2JriFK5qEjkEpFe1A7CK+9t7/xo6uSvpFfRLNXw/Y6z4F0LY4JLwNkiwcfgkUidBjrfpdopkQ4cgLXcoYE0/lNqyIsuv9jm8X2QZDEKejex1wnZGX9yYBR5tNVeaZs0+qW+aIYs8o17Dql4tDxdQFGr5vGJCBAPQ+7YYBIFiufqNrqTjjNQiSg63ccmBQnfSajRVkhgL91HmMczIqOpv427N5dDhj9ACUPvOykFR3+a2dQ28FwUE6HNzVpmWOon1vpVri/Ut/NyBMg1PfKoGyG5jW3Mb7lBtwCTjsvgsD21q+GY1pj4ommx2eeFtRMKsBn2u42HTTxQUJIpmYWeiLu8+KMZo2vlbJYpxugg7dKPe8ghkpTB392nrVHsGmcjTqXclmPwpRMgvy8XZSOZKAA0EPt/dBI82ZzHxW8mR+gOLghjba7J9NbQoHniEuH9VZwHRAFw5mSAf4wFmf3xCH6kCGLOgOe+82lrpHtATOaxEOudwkqo8CqlPVzuGYT6ooDBkaD9A/o9Cs5xP+P2geSODb8ThnxcjXf3dU60=
  file:
  - cv.pdf
  skip_cleanup: true
  on:
    tags: true
